// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxwlzslnbslhetcupax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueHdsenNsbmJzbGhldGN1cGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTIwOTAsImV4cCI6MjA2MDQ2ODA5MH0.yaFj1-qqmcnnRQVTJutn9IH9vi_cWAsy9JTGsb3zWso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);